### ISSUE TITLE
Whenever I try randomize a game I get an unhandled exception.

### ISSUE THREAD

**Issue by spinbotters** [Ajarmar/universal-pokemon-randomizer-zx#31]
After I select where the file is gonna be saved to it starts and then a second later stops and gives me a message, I've checked the launcher logs to see if it had any info but they were empty and I've tried both Alpha Sapphire and Ultra Moon to see if it's an issue with my games but other than I don't know.
[error_2020-10-12-18-15-35.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5363081/error_2020-10-12-18-15-35.txt)
[error_2020-10-12-18-23-56.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5363082/error_2020-10-12-18-23-56.txt)
![java_N9gBgPiWlC](https://user-images.githubusercontent.com/62416638/95708532-04909780-0cb9-11eb-9446-2db145a40f45.png)

**Comment by forsetite** [comment]
I get this too when randomising Black
[error_2020-10-12-21-02-49.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5364464/error_2020-10-12-21-02-49.txt)
[error_2020-10-12-21-04-25.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5364466/error_2020-10-12-21-04-25.txt)
[error_2020-10-12-20-59-11.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5364468/error_2020-10-12-20-59-11.txt)

**Comment by Ajarmar** [comment]
Yeah, there's currently a problem that occurs when Global 1-to-1 Mapping is used without Allow Alternate Formes. That'll be fixed in the next release, so thanks for pointing it out.

The Alpha Sapphire issue is different though, and it's a bit weird - we haven't been able to reproduce it, and we're not sure what the cause could be. Can you (@spinbotters) try using Global 1-to-1 Mapping with Allow Alternate Formes and see if that works for Alpha Sapphire?

**Comment by spinbotters** [comment]
Enabling Allow Alternate Formes fixed Ultra Moon but still crashed with Alpha Sapphire.

**Comment by Ajarmar** [comment]
I'm still confused by the Alpha Sapphire error - we haven't been able to recreate it at all, so it may be the case that your ROM is corrupted (although it's a weird coincidence that the error happens close to where the other error you posted happens...)

I would recommend trying to find a new Alpha Sapphire ROM or trying out different settings.

**Comment by gymleadernate** [comment]
Hi there! I have the same issue with Alpha Sapphire and I dumped the game myself from my cart. Just wanted to chime in and make it known that it wasn't an isolated issue. However, the suggested fix of Global 1-1 and Allow Alternate Formes worked like a charm. Cheers!

**Comment by Ajarmar** [comment]
Closing this since it's more or less resolved
