### ISSUE TITLE
[Bug] Application does not open on Wayland

### ISSUE THREAD

**Issue by ItsRogueRen** [Ajarmar/universal-pokemon-randomizer-zx#812]
**Describe the bug**
Launcher for unix fails to launch the application and spit and error about X11. I am running on Wayland so the app may not know how to run in Wayland or how to use xwayland instead. 

**To Reproduce**
1. Launch a wayland session
2. Double click on 'launcher_UNIX.sh'
3. Launcher does not open

**Expected behavior**
The application to open with a window

**Screenshots**

**System (please complete the following information):**
 - Operating System: Linux (Nobara 41)
 - Java Version: 23
 - Randomizer Version: 4.6.1

**Additional context**
When run from the terminal via `./launcher_UNIX.sh` the following error is displayed

```
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$main$117(NewRandomizerGUI.java:3994)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tragediany** [comment]
This is not a bug with this specific application. To mitigate this install the full JDK package.
For example in Fedora this would fix the issue.
`sudo dnf install java-21-openjdk`
This most likely works with Nobara as well.

Fixed my same issue by referring to a Fedora discussions forum thread here https://discussion.fedoraproject.org/t/cannot-run-java-jar-file-in-wayland-only-fedora-40/111814

**Comment by Plague-Lord-Ardof** [comment]
> This is not a bug with this specific application. To mitigate this install the full JDK package. For example in Fedora this would fix the issue. `sudo dnf install java-21-openjdk` This most likely works with Nobara as well.
> 
> Fixed my same issue by referring to a Fedora discussions forum thread here https://discussion.fedoraproject.org/t/cannot-run-java-jar-file-in-wayland-only-fedora-40/111814

I created this account just to say this: THANK YOU! I've been bashing my head on my desk for 3 days trying to get this damn thing to work! Thank you!

**Comment by kingminor** [comment]
I am having this issue as well on nobara. I tried the fix sudgested by  @tragediany however I am still getting same error.
